# Generated by Django 5.1.3 on 2024-11-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_contact_delete_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booknow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=100)),
                ('member_count', models.IntegerField()),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
