# Generated by Django 5.1.3 on 2025-02-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booknow_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('your_name', models.CharField(max_length=100)),
                ('your_email', models.EmailField(max_length=100, unique=True)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('guests', models.IntegerField()),
            ],
        ),
    ]
