# Generated by Django 5.1.3 on 2025-12-05 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_roombook_created_at_roombook_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booknow',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booknow',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booknow',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
