# Generated by Django 5.1.3 on 2026-03-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booknow_user_contact_message_contact_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='email_status',
            field=models.CharField(default='Unsent', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_status',
            field=models.CharField(default='Unsent', max_length=10),
        ),
        migrations.AddField(
            model_name='roombook',
            name='email_status',
            field=models.CharField(default='Unsent', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
